### Root user
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwNjllZWEyYWNkOTg0MjhmYzcwN2E2YiIsImlhdCI6MTYxNzU2NTM1MX0.i4JhP28HmTvlDnBH8V9nA-f43dhnE9mYAFaghLDsfG8


{
  "title": "Reddit",
  "author": "magink",
  "url": "www.reddit.com",
  "likes": "16",
  "userId": "6069eea2acd98428fc707a6b" 

}

### terminator user

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Sweclockers",
  "author": "magink",
  "url": "www.sweclockers.com",
  "likes": "12",
  "userId": "6069eeb0acd98428fc707a6c"

}

### user_01

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Fragzone",
  "author": "magink",
  "url": "www.fz.com",
  "likes": "76",
  "userId": "6069eeb1acd98428fc707a6d"

}

### 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "YR",
  "author": "Norway",
  "url": "www.yr.no",
  "likes": "34",
  "userId": "6069eeb1acd98428fc707a6d"

}