### terminator user

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcm1pbmF0b3IiLCJpZCI6IjYwNmE1OTBmOTZkZDliMjQ3ODA2YTEyNSIsImlhdCI6MTYxNzU4MjM3Mn0.klBkhRdVRTG3GL8ssFiiT18RU3em3wHN9BwJZegip7Q

{
  "title": "Fragzone",
  "author": "Joakim Bennet",
  "url": "www.fz.se",
  "likes": "65",
  "userId": "6069eeb0acd98428fc707a6c"

}
