POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "testing1234"
}
### 
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "terminator",
    "name": "Douglas McCrachah",
    "password": "134ghsd"
}

### 
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "user_01",
    "name": "Sumgam 1",
    "password": "argasdfg"
}